---
version: '2'
services:
    example:
        image: juanito/presenter
        ports:
            - 8000:8000
        volumes:
            - ./example/images:/opt/presentation/images
            - ./example/slides:/opt/presentation/slides
        command:
            "grunt serve"
